# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
pod 'MWPhotoBrowser', '~> 2.1.2'
target 'PYtupianchakanqi' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PYtupianchakanqi

  target 'PYtupianchakanqiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PYtupianchakanqiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
